version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - DB_HOST=db
    - DB_NAME=db
    - DB_USER=user
    - DB_PASSWORD=password
    - ENVIRONMENT=dev
    - STATSD_HOST=localhost
    - STATSD_PORT=8125
    ports:
    - "5003:80"
    volumes:
    - .:/app
    links:
    - db
  db:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    ports:
    - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

volumes:
  dbdata:
